##########
# collectionbuilder-contentdm
# Jekyll Digital Collection Generator, designed as a skin over CONTENTdm
# https://github.com/CollectionBuilder/collectionbuilder-contentdm
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://www.lib.uidaho.edu
# location on the website, normally in /digital
# e.g. /digital/hjccc
baseurl: /digital/1918flu
# location of code, the full url to your github repository
source-code: https://github.com/uidaholib/collectionbuilder-cdm-template
# url to the shared assets folder on Digital
digital-assets: https://www.lib.uidaho.edu/assets


##########
# SITE SETTINGS
#
# title of site appears in banner
title: 1918 Flu Pandemic Collection
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Materials depicting the impact of the "Spanish Flu" on the University of Idaho
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "In 1918, a virulent strain of influenza affected approximately 500 million individuals worldwide. The disease reached the University of Idaho in October of that year, prompting the university to cancel activities, enact a quarantine, and encourage the use of gauze face masks. The 1918 Flu Pandemic Collection brings together correspondence, reports, news articles, oral histories, and other materials that highlight the local response to the 1918 pandemic."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: dcnb
# Organization branding
organization-name: "Digital Initiatives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png


##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: 1918flu 
# contentdm collection name, matches collection ID used by CDM
# CONTENTdm server url
#cdm-url: https://digital.lib.uidaho.edu

# digital objects location
digital-objects: https://webpages.uidaho.edu/library/spec/objects/1918flu

# page generation settings 
# "data" value must be the name of the metadata file (other values should be not be changed)
page_gen:
  - data: '1918flu'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html' 
    filter: 'objectid'  

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
